# Generated by Django 3.1.4 on 2020-12-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
