# Generated by Django 3.1.4 on 2020-12-01 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
