# Generated by Django 3.1.4 on 2020-12-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_user_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
