# Generated by Django 3.1.4 on 2020-12-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20201202_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bid_user',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='username',
            field=models.CharField(max_length=64),
        ),
        migrations.RemoveField(
            model_name='user',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(to='auctions.Listing'),
        ),
    ]
