# Generated by Django 3.1.4 on 2020-12-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20201202_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bid_user',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
